### ISSUE TITLE
ERROR: type "raster" does not exist. 

### ISSUE THREAD

**Issue by constant5** [postgis/docker-postgis#138]
I am trying to import some raster data into the dockerized database and I am getting this error.  From the web it seems that the rtpostgis script needs to run to enable this type.

**Comment by phillipross** [comment]
Hi @constant5 is this still an issue?

**Comment by phillipross** [comment]
@constant5 Due to lack of activity, I'm going to close out this issue.  Feel free to open a new issue after trying the latest versions.  And also make sure you're trying with a postgis v3.x image as the 2.x images currently do not support the raster extension.

**Comment by NiklasKeck** [comment]
I came across the same issue today. Turns out the postgis_raster extension is not part of the main postgis extension anymore and thus not enabled by default (e.g. https://info.crunchydata.com/blog/waiting-for-postgis-3-separate-raster-extension). The following works for me:

`CREATE EXTENSION postgis_raster;`
