### ISSUE TITLE
pg_config reports invalid paths for 11.0

### ISSUE THREAD

**Issue by Nogbit** [postgis/docker-postgis#161]
I'm using `mdillon/postgis:1`.

I then install pg_config while in the container
`apt-get update && apt-get --yes install libpq-dev`

I then run `pg_config` and get the following.
`PKGLIBDIR = /usr/lib/postgresql/12/lib`

That's not a valid path and instead I expect to see the following.  
`PKGLIBDIR = /usr/lib/postgresql/11/lib`

Any suggestions on how to fix this?

**Comment by phillipross** [comment]
I suspect what is happening is that you aren't specifying the version of libpq-dev to install, so the latest version is what is getting installed instead of the version you are expecting.

It looks like you typoed the image tag so i'm assuming you meant `mdillon/postgis:11`

In which case, make sure you've run `apt-get update` and then query specific versions of libpq:
```
apt-cache policy libpq-dev
```
and then install the version that matches the image, in this case it'd be a v11:
```
apt-get install libpq-dev=11.6-1.pgdg90+1 
```
But you'll probably get an error about version-specific dependencies or something, so try:
```
apt-get install libpq-dev=11.6-1.pgdg90+1 libpq5=11.6-1.pgdg90+1
```

Hope that helps!
```

**Comment by Nogbit** [comment]
It was my bad, attaching a previously used disk that had an attempt at a different version resulting in the extra directories.
