### ISSUE TITLE
No shp2pgsql in installation

### ISSUE THREAD

**Issue by Jake-Gillberg** [postgis/docker-postgis#222]
In trying to use this image to work through the [postgis installation manual](https://postgis.net/docs/manual-3.1/postgis_installation.html#loading_extras_tiger_geocoder), I ran into the unexpected result of having to `apt-get install postgis` to get shp2pgsql.

**Comment by phillipross** [comment]
This is correct.  In order to keep the container image small (optimal for scaling production environments) not all of the utilities or libraries available for postgis are currently included in the current image.  Please see issue #224 for further reference.

The idea of maintaining multiple images exists which could effectively provide both smaller tighter images optimized for production as well as larger images that include more for development, demo environments, etc.  Hopefully in the near future we can bootstrap some discussions around this and put a plan in place for accomplishing this 🤞

**Comment by Jake-Gillberg** [comment]
Thanks, makes sense!
