### ISSUE TITLE
POSTGIS_VERSION increments keep breaking build pipeline

### ISSUE THREAD

**Issue by aaron-manning** [postgis/docker-postgis#310]
Hi,

As you do not provide builds for ARM64, I have to build from your dockerfile in my deploy pipeline.
This isn't a problem, it's been working great over the last few months, but a problem I keep facing is that whenever you increment the POSTGIS_VERSION in your dockerfile, the previous upstream package is no longer available and it breaks my build pipeline.

This is the dockerfile I use:
https://github.com/postgis/docker-postgis/blob/master/14-3.2/Dockerfile

Is anyone able to advise on a way to not have my build pipeline keep breaking? Perhaps you could leave the old package up, or is there a stable version that does not get removed on every minor version increase?

I had a look through https://www.debian.org/distrib/packages but all I can find is the latest version used in the dockerfile, which changes quite frequently and the old version becomes unavailable.

I would like to avoid having to pull your dockerfile as part of my build pipeline as it removes the ability for me to lock-in a postgis version.

Thanks

**Comment by phillipross** [comment]
@aaron-manning I apologize in advance if I'm misunderstanding your exact issue, but I think maybe your challenges are caused by the fact that the postgis packages actually change in the debian repo.  We're impacted by this in the docker-postgis project here as well.

We have no direct control over the postgis packages in the debian repo.  When the packages are changed, we have to update things here to match when the debian repos change.  It's just something we work around and try to automate as much as possible, but it's not 100% automatic.  We run a pre-scheduled CI build in this repo which periodically triggers a build process to see if the packages have changed.  When this build fails, it's an indicator that the packages have changed and we have to run the update script to match the new upstream packages.

I understand you're probably aiming for a 100% automated solution, which might be possible if you look at our update script in this repo and make it part of your build, but you'll have to analyze the impacts on your own.  We explicitly don't automate the update as it's preferential for us to be forced to look at, review, and maybe test when the packages change before we try to build and push to dockerhub.

Hope that helps!

**Comment by aaron-manning** [comment]
@phillipross, you understood my issue perfectly.

If this is how you solve the problem, I'm guessing it's because you too have been unable to find a stable source of the postgis package.

I'll have to look into other options until you are able to get an arm64 build up on docker.

Feel free to close this issue unless you think it's worth leaving open for an eventual solution.

Thanks
